name: AnvilUI
version: 1.0.0
api: [5.0.0]
author: Will
main: Will\AnvilUI
description: AnvilUI plugin for repairing and renaming tools and armor using EconomyAPI.
softdepend: [EconomyAPI, FormAPI]

commands:
  anvilui:
    description: Open the AnvilUI menu
    usage: /anvilui
    permission: anvilui.command

permissions:
  anvilui.command:
    description: Allows players to use the /anvilui command
    default: true
